### ISSUE TITLE
Incorrect reference to tickDamage in status_hyper2

### ISSUE THREAD

**Issue by jtgibson01** [IrisBlanche/EnhancedTemperature-Vanilla#11]
status_hyper2.statuseffect refers to "tickDamage" rather than "healthDamage", meaning that you begin suffering 1 point of damage per 20 ticks (1/3 second) at hyperthermia level 50.  As the default script assigns "tickDamage" to 0 and all the other status effects correctly refer to healthDamage, I believe this is in error.

**Comment by IrisBlanche** [comment]
Oh it seems it was a remnant from something else i tried in EHTs early stage before i moved it to github x)

fyi it's exposure 50 which refers to hyperthermia stage 2. Hyperthermia level 50 is non-existent ;)
